### ISSUE TITLE
Extend API:  "latest"

### ISSUE THREAD

**Issue by amcedwards** [intuit/ami-query#1]
Would it be possible to extend the API to return only the latest AMI?  

I recognize that this is a can of worms, given that "latest AMI" could alternately mean "give me the latest HVM RHEL6.7 AMI" or "give me the latest RHEL7 AMI" -- maybe it comes down to only returning one ordered result based on the filtering query that is presented.

Thoughts?

**Comment by jmassara** [comment]
Agreed that `latest` by itself would be ambiguous. A `latest` boolean query parameter could limit the result to the newest AMI of a given type - which could yield multiple results.  I think it's reasonable for the end user to have to specify which `latest` version they want, e.g.: `?latest&tag=osVersion:rhel7.2`.  `latest` would also assume the `status` tag was set to `available`.

/cc @brettweavnet-intuit

**Comment by bw-intuit** [comment]
My initial thinking is using latest could be confusing (do the ambiguity you describe).  What is the impact to leaving this up to the client to parse?

If we were going to add this my initial thinking is we may want to add it as a results or limit parameter that can be used to limit the results returned.  This could be set to 1 and combined with other query options to provide a "latest" functionality.

Will think on it a bit more....

**Comment by bw-intuit** [comment]
^^ cc/ @jmassara @amcedwards

**Comment by amcedwards** [comment]
@brettweavnet-intuit, @jmassara -- 

I consider this a nice-to-have as opposed to a must-have because "latest" can be discerned by a thoughtful end-user.  For instance, today, I'm using a query that filters by available, a specific region, and type (HVM), then sorts on CreationDate attribute, pulling the first item off the list, like:

```
[{id, creationDate: ( if .tags.creationDate != null then .tags.creationDate | tonumber | todate else null end )}] | sort_by(.creationDate) | reverse | .[0] | "Latest AMI in " + .region + " is: " + .id + " (Created: " + .creationDate + ")"'\''
```

**Comment by bw-intuit** [comment]
@amcedwards my initial thinking is it would be hard to include all of that logic into a single flag, I would lean to for adding multiple flags which can be composed to match the client side logic.  For example:
- Sort By
- Sort Order
- Limit Results

Let me noodle on it a bit...

**Comment by jmassara** [comment]
Closing. If there is still a need, please re-open.
